# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# you need copy this file to your hexo blog root path , rename Anisina_config to _config and replace or modify origin _config.yml

# Site
title: 布袋知诺 
subtitle: 知行诺一
description: 易知 简能
author: zhinuo
language: zh-CN
timezone: Asia/Shanghai

# custom Site settings
# more detail check out docs
SEOTitle: 布袋知诺 知行诺一
header-img:  # header-img.png 
email: brux4me@gmail.com # your email
keyword: 布袋知诺 知行诺一 # your keywords
# custom end


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.zhinuo.space
root: /
permalink: article/:abbrlink.html    # :category-:abbrlink.html    # :category/:id.html    # :id-:title.html
permalink_default:
  lang: zh-CN

# Header
menu:
  Home: /
  categories: /categories
  tags: /tags
  Rss: /rss2.xml    #  /atom.xml

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag 分类项为 单字 时 且 lang: zh-CN 下面的英语为翻译
default_category: uncategorized
category_map:
    记: writing
    悟: spark
    经: essence
    摘: excerpt
    杂: MISC
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY年MM月DD日 @ HH:mm
time_format: HH时mm分

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

topindex_generator:
  per_page: 10
  order_by: -date

jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: true
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true
    
# Extensions
## Plugins: https://hexo.io/plugins/
# Plugins:


# Miscellaneous

#sitemap
sitemap:
  path: sitemap.xml
  tag: false
  category: false

#Feed Atom
feed:
  type: rss2     # atom
  path: rss2.xml # atom.xml
  limit: 1000000

## Themes: https://hexo.io/themes/
theme: indigocard

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy: # github coding 同时部署  多个 deploy 要使用 — type
- type: git
  repository: 
      github: git@gitwgm:wegome/wegome.github.io.git,master
      coding: git@codingbdm:budaim/budaim.git,coding-pages
- type: baidu_url_submitter

# Security
## https://github.com/MikeCoder/hexo-blog-encrypt 密码不能为纯数字 1.1.10版已修正
encrypt:
  enable: true
  default_abstract: 本文已隐藏, 请输入密码浏览.</br>
  default_message: 您好, 请输入密码浏览.

# abbrlink config
abbrlink:
  alg: crc32  #support crc16(default) and crc32
  # rep: hex    #support dec(default) and hex
  # crc32 & hex e.g. https://post.zz173.com/posts/8ddf18fb.html
  # crc32 & dec e.g. https://post.zz173.com/posts/1690090958.html

baidu_url_submit:
  count: 3 ## 比如3，代表提交最新的三个链接
  host: www.zhinuo.space ## 在百度站长平台中注册的域名
  token: L4PiiYWHNRZdoIF8 ## 请注意这是您的秘钥，请不要发布在公众仓库里!
  path: baidu_urls.txt ## 文本文档的地址，新链接会保存在此文本文档里

lazyload:
  enable: true
  onlypost: true
  loadingImg: /images/loading.png


# hexo-generator-amp
# The following settings is the quick start options.
generator_amp:
  templateDir:  amp-template
  assetDistDir: amp-dist
  logo:
    path: sample/sample-logo.png
    width: 600 # width <= 600px
    height: 60  # width <= 60px
  substituteTitleImage:
    path: sample/sample-substituteTitleImage.png
    width: 1024 # width >= 696px
    height: 800
  placeholderImg:
    path: sample/sample-placeholder.png
  generateAmpPath: amp/article/:abbrlink.html   #(optional) Custom AMP HTML Path
  theme:
    menu:   #(optional) Sample AMP template's menu option
      首页: /   #(optional) example menu
      归档: /archives   #(optional) example menu
      #about: /about
      #tags: /tags
      #categories: /categories
      #links: /links
      自话: /intro
      博萃: /blogroll
    category_posts: false   #(optional) Enable category posts
    category_posts_detailed: false   #(optional) Enable detailed category posts
    latests: true   #(optional) Enable latests posts
    list_limts: 3   #(optional) This option limit the number of display in the above lists (default:5)
  cache: hexo-generator-amp-cached.json   #(optional) Enable cache (Improve generation speed)
